"""Adds raw FB message table

Revision ID: 519386cc9516
Revises: 969cd6f35744
Create Date: 2017-04-16 09:14:16.994043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519386cc9516'
down_revision = '969cd6f35744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_fb_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_fb_message')
    # ### end Alembic commands ###
