"""Removes tag.name in favor of tag.title and tag.alias

Revision ID: a0202a937831
Revises: c7c684d27af9
Create Date: 2017-04-27 22:41:54.978883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0202a937831'
down_revision = 'c7c684d27af9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('alias', sa.String(length=255), nullable=True))
    op.add_column('tag', sa.Column('title', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_tag_alias'), 'tag', ['alias'], unique=False)
    op.drop_index('ix_tag_name', table_name='tag')
    op.drop_column('tag', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_tag_name', 'tag', ['name'], unique=False)
    op.drop_index(op.f('ix_tag_alias'), table_name='tag')
    op.drop_column('tag', 'title')
    op.drop_column('tag', 'alias')
    # ### end Alembic commands ###
