"""empty message

Revision ID: a6db32044d2a
Revises: 969cd6f35744
Create Date: 2017-04-16 10:08:02.707700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a6db32044d2a'
down_revision = '969cd6f35744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_fb_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_fb_message')
    # ### end Alembic commands ###
