"""Adds the business, tag, and business_tag tables.

Revision ID: c7c684d27af9
Revises: 266930f92d64
Create Date: 2017-04-27 21:18:56.696037

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c7c684d27af9'
down_revision = '266930f92d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_yelp_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('yelp_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_name'), 'business', ['name'], unique=False)
    op.create_index(op.f('ix_business_price'), 'business', ['price'], unique=False)
    op.create_index(op.f('ix_business_yelp_id'), 'business', ['yelp_id'], unique=True)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=False)
    op.create_table('business_tag',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('business_id', 'tag_id')
    )
    op.alter_column(u'raw_ai_message', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_tag')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_business_yelp_id'), table_name='business')
    op.drop_index(op.f('ix_business_price'), table_name='business')
    op.drop_index(op.f('ix_business_name'), table_name='business')
    op.drop_table('business')
    # ### end Alembic commands ###
